AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - bin/bundle

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 128
