AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - bin/bundle
    - vendor/**/*

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 128

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: space
  
Metrics/BlockLength:
  Exclude:
    - spec/**/*

Naming/MethodParameterName:
  AllowedNames:
    - x
    - y