AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  ExtraDetails: true
  Exclude:
    - bin/bundle
    - vendor/**/*

Layout/CaseIndentation:
  IndentOneStep: true

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Max: 128

Layout/SpaceAroundOperators:
  AllowForAlignment: true

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: space

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Naming/MethodParameterName:
  AllowedNames:
    - x
    - y

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

