AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - bin/bundle
    - vendor
  Include:
    - Gemfile
    - Rakefile
    - aoc2021.gemspec
    - bin
    - exe
    - lib/**/*.rb
    - spec/*.rb

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 128

Metrics/BlockLength:
  Exclude:
    - spec/*
