AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  ExtraDetails: true
  Exclude:
    - bin/bundle
    - vendor/**/*
    - lib/aoc2021/puzzles/amphipod.rb
    - lib/aoc2021/puzzles/arithmetic_logic_unit.rb
    - lib/aoc2021/puzzles/chitons.rb
    - lib/aoc2021/puzzles/dirac_dice.rb
    - lib/aoc2021/puzzles/packet_decoder.rb
    - lib/aoc2021/puzzles/reactor_reboot.rb
    - lib/aoc2021/puzzles/sea_cucumber.rb
    - lib/aoc2021/puzzles/snailfish.rb
    - lib/aoc2021/puzzles/trench_map.rb

Layout/CaseIndentation:
  IndentOneStep: true

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Max: 128

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned

Layout/SpaceAroundOperators:
  Enabled: false

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: space

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Naming/BlockForwarding:
  EnforcedStyle: explicit

Naming/MethodParameterName:
  AllowedNames:
    - i
    - w
    - x
    - y
    - z
    - md

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/MixinUsage:
  Exclude:
    - spec/**/*

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/TernaryParentheses:
  Exclude:
    - lib/aoc2021/puzzles/amphipod.rb
